#cloud-config
package_update: true
ssh_pwauth: true

users:
  - name: '${vm_username}'
    plain_text_passwd: '${vm_password}'
    lock_passwd: false
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash

packages:
  - nginx

write_files:
  - path: /etc/nginx/sites-available/default
    permissions: '0644'
    owner: root:root
    content: |
      upstream backends {
      %{ for ip in backend_ips ~}
          server ${ip}:80;
      %{ endfor ~}
      }

      server {
          listen 80;

          location / {
              proxy_pass http://backends;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
          }
      }

runcmd:
  - systemctl restart nginx
